model_name_or_path: Qwen/Qwen2.5-Coder-1.5B

stage: sft
do_train: true
finetuning_type: lora
lora_target: all

dataset: solidity2_pyano_train
template: qwen
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16
use_fast_tokenizer: true

output_dir: ./finetuned/qwen_2.5_1.5B_sft_lora_solidity2
logging_steps: 500
save_steps: 2500
plot_loss: true
overwrite_output_dir: true
overwrite_cache: true

per_device_train_batch_size: 1
learning_rate: 0.000005
weight_decay: 0.1
num_train_epochs: 50
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 90000

val_size: 0.05
per_device_eval_batch_size: 1
eval_steps: 500

report_to: wandb
run_name: qwen_2.5_1.5B_sft_lora_sol2